name: ecommerce_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.3 <4.0.0"

#--------------- PACKAGES ------------------#
dependencies:
  cached_network_image: ^3.3.1
  capped_progress_indicator: ^0.0.2
  carousel_slider: ^4.2.1
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.19.2
  firebase_cloud_firestore: ^4.15.8
  firebase_core: ^2.30.0
  firebase_storage: ^11.7.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  google_sign_in: ^6.2.1
  http: ^1.1.0
  iconsax: ^0.0.8
  image_picker: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  lottie: ^3.1.0
  readmore: ^3.0.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/lottie/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
