// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFVA20PShWBRAhu3H3fmmOGub67eDci8c',
    appId: '1:618402495919:web:a799ad6e3e7cbb0e1e035a',
    messagingSenderId: '618402495919',
    projectId: 'ecommerce-90a74',
    authDomain: 'ecommerce-90a74.firebaseapp.com',
    storageBucket: 'ecommerce-90a74.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFkVy6udF91TA4TIQnKwQ32tB4vOSo3Ac',
    appId: '1:618402495919:android:c7371306a79e47031e035a',
    messagingSenderId: '618402495919',
    projectId: 'ecommerce-90a74',
    storageBucket: 'ecommerce-90a74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS2-Ua3jPFg4LfntHyDVaE_EkOdErbu5s',
    appId: '1:618402495919:ios:575bbb922dbab4731e035a',
    messagingSenderId: '618402495919',
    projectId: 'ecommerce-90a74',
    storageBucket: 'ecommerce-90a74.appspot.com',
    androidClientId: '618402495919-srf5edqa5m1c7h65pmg30m8fbjgl34s1.apps.googleusercontent.com',
    iosClientId: '618402495919-d6j2mc814mhtr8aggol6fit4uf8m62ph.apps.googleusercontent.com',
    iosBundleId: 'com.aichat.ecommerceFlutter',
  );
}
